HW-7 BackOff, Retry and limiting
danek0100/Tinkoff-Backend-course pull request #12
Opened 2024-03-30 20:27 UTC by danek0100

2024-04-07 11:00 UTC, lwbeamer requested changes
Насчет разного вида политик - ОК, ведь в боте у тебя HttpClient, и встроенные инструменты из reactor туда (как я понял) не применить

2024-04-07 11:00 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/configuration/BackOffConfig.java
> +        };
Вместо этого как раз используют `@ConditionalOnProperty`)

2024-04-07 11:00 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/controller/BotApiController.java
> +        String ip = request.getRemoteAddr();
А тут точно будет все время разный реквест? Контроллер же создается как синглтон бин и сразу внедряет HttpServletRequest, которые не изменяется. Или нет?

2024-04-07 11:00 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/controller/BotApiController.java
>      public ResponseEntity<?> postUpdate(@RequestBody LinkUpdateRequest linkUpdate) {
Можно передать запрос в качестве параметра метода, так: 
 
`public ResponseEntity<?> postUpdate(@RequestBody LinkUpdateRequest linkUpdate, HttpServletRequest request) {`

Не знаю работает ли твой способ (коммент выше), но выглядит так, что запрос внедряется один раз и больше не изменяется (поправь если это не так)

2024-04-07 11:00 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/configuration/RetryConfig.java
> +    }
Судя по доке это экспоненциальная политика повтора. Где еще две?)

Можно сделать конфигурируемо как в боте (с выбором из проперти)

2024-04-14 08:19 UTC, danek0100 commented on bot/src/main/java/edu/java/bot/configuration/BackOffConfig.java
> +        };
Сделал. Спасибо)

2024-04-14 08:44 UTC, danek0100 commented on bot/src/main/java/edu/java/bot/controller/BotApiController.java
> +        String ip = request.getRemoteAddr();
HttpServlet действительно один и внедряется при создании, кажется, что должен обновляться контекст запроса. Без разных исходящих ip не смог проверить.

2024-04-14 08:47 UTC, danek0100 commented on bot/src/main/java/edu/java/bot/controller/BotApiController.java
>      public ResponseEntity<?> postUpdate(@RequestBody LinkUpdateRequest linkUpdate) {
Попробовал:
`public ResponseEntity<?> postUpdate(@RequestBody LinkUpdateRequest linkUpdate, HttpServletRequest request) {`

И:
```
private boolean isLimitExceeded() {
    HttpServletRequest request = ((ServletRequestAttributes) RequestContextHolder.getRequestAttributes()).getRequest();
    String ip = request.getRemoteAddr();
    Bucket bucket = bucketManager.resolveBucket(ip);
    return !bucket.tryConsumeAndReturnRemaining(1).isConsumed();
}
```

В обоих случаях HttpServletRequest передаётся одинаковый объект в разных запросах, однако различается RequestFacade от запроса к запросу. Остановился на первом способе)

2024-04-14 09:14 UTC, danek0100 commented on scrapper/src/main/java/edu/java/configuration/RetryConfig.java
> +    }
Добавил конфигурацию из проперти. Добавил jitter, и const стратегию. Линейную быстро добавить не вышло(

2024-04-16 08:04 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/configuration/RetryConfig.java
> +    }
> Добавил конфигурацию из проперти. Добавил jitter, и const стратегию. Линейную быстро добавить не вышло(

Там в реакторе если встроенной нет, можно передать свою функцию в качестве политики, в которой руками прописать линейный ретрай. 

https://projectreactor.io/docs/core/release/api/reactor/util/retry/Retry.html#from-java.util.function.Function-

но если быстро не получится то в целом ок, потому что ты сделал это в боте и формально в твоем дз оно есть

2024-04-20 09:13 UTC, merged