HW 3: REST
danek0100/Tinkoff-Backend-course pull request #6
Opened 2024-03-03 11:45 UTC by danek0100

2024-03-08 14:28 UTC, lwbeamer requested changes
На самом деле соответствие контракту важная штука, без которой в реальных проектах можно наплодить много проблем, потому что те кто завязан на твое приложения будут получать/отправлять не то, под что у них уже написан свой код

2024-03-08 14:28 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/controller/BotApiController.java
> +        return ResponseEntity.ok().body("Обновление обработано");
У тебя тут в ответе придет тело со строкой внутри, но по спецификации тела в ответе быть не должно, поэтому тело возвращать не нужно. На скрине просто описание с точки зрения спецификации (для понимания), это не содержимое ответа)
<img width="272" alt="image" src="https://github.com/danek0100/Tinkoff-Backend-course/assets/73843667/1886ed78-d61b-45dd-a2af-5af800170085">

2024-03-08 14:28 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/dto/AddLinkRequest.java
> +@Data
Учитывая что уже прописаны геттеры и сеттеры, то аннотация `@Data` кажется избыточной и вводит в заблуждение

2024-03-08 14:28 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/dto/ApiErrorResponse.java
> +@Data
Тут и во всех остальных dto с ней аналогично

2024-03-08 14:28 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/exception/GlobalExceptionHandler.java
> +        response.setExceptionMessage(ex.getMessage());
Для того же кода, но более в чистом виде частенько используют `@Builder` из lombok, но можешь не исправлять

2024-03-08 14:28 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/client/ScrapperApiClient.java
> +        this.httpClient = httpClient != null ? httpClient : HttpClient.newHttpClient();
Ты этот бин регистрируешь в `HttpClientConfig`, не доверяешь спрингу или зачем проверка на null и создание вручную?)

2024-03-08 14:28 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/client/ScrapperApiClient.java
> +        this.objectMapper = objectMapper != null ? objectMapper : new ObjectMapper();
Подозреваю что этот бин по-дефолту есть в контексте спринга и такое опционально создание вручную здесь тоже не нужно. Если что-то пойдет не так и нужного бина не будет, но спринг об этот предупредит и приложение не запустится, это нормально

2024-03-08 14:28 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/controller/ScrapperApiController.java
> +        return ResponseEntity.ok().body("Чат зарегистрирован");
Тоже не должно быть тела

2024-03-08 14:28 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/controller/ScrapperApiController.java
> +        return ResponseEntity.ok().body("Чат успешно удалён");
И здесь

2024-03-08 14:28 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/controller/ScrapperApiController.java
> +    }
Должен возвращать ListLinksResponse по спеке

2024-03-08 14:28 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/controller/ScrapperApiController.java
> +    }
А здесь LinkResponse

2024-03-08 14:28 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/controller/ScrapperApiController.java
> +}
Тоже LinkResponse

2024-03-10 12:54 UTC, danek0100 commented on bot/src/main/java/edu/java/bot/dto/AddLinkRequest.java
> +@Data
Убрал

2024-03-10 12:55 UTC, danek0100 commented on bot/src/main/java/edu/java/bot/dto/ApiErrorResponse.java
> +@Data
Аналогично во всех случаях

2024-03-10 13:18 UTC, danek0100 commented on bot/src/main/java/edu/java/bot/exception/GlobalExceptionHandler.java
> +        response.setExceptionMessage(ex.getMessage());
Использовал `@Builder`, спасибо!

2024-03-10 13:20 UTC, danek0100 commented on bot/src/main/java/edu/java/bot/client/ScrapperApiClient.java
> +        this.httpClient = httpClient != null ? httpClient : HttpClient.newHttpClient();
Были проблемы с мок-бинами для тестов, тогда это помогло исправить проблемы внедрения. Попробую сделать лучше

2024-03-10 13:27 UTC, danek0100 commented on bot/src/main/java/edu/java/bot/client/ScrapperApiClient.java
> +        this.objectMapper = objectMapper != null ? objectMapper : new ObjectMapper();
На данный момент тесты проходят без этого условия. Удалил, так как сейчас в этом коде нет необходимости)

2024-03-10 13:36 UTC, danek0100 commented on bot/src/main/java/edu/java/bot/controller/BotApiController.java
> +        return ResponseEntity.ok().body("Обновление обработано");
Убрал, спасибо!

2024-03-10 13:38 UTC, danek0100 commented on scrapper/src/main/java/edu/java/controller/ScrapperApiController.java
> +        return ResponseEntity.ok().body("Чат зарегистрирован");
Убрал тело в ответе

2024-03-10 13:38 UTC, danek0100 commented on scrapper/src/main/java/edu/java/controller/ScrapperApiController.java
> +        return ResponseEntity.ok().body("Чат успешно удалён");
Убрал тело в ответе

2024-03-10 13:43 UTC, danek0100 commented on scrapper/src/main/java/edu/java/controller/ScrapperApiController.java
> +    }
Делал пока как заглушки, что просто проверить. Установил правильный возвращаемый тип

2024-03-10 13:46 UTC, danek0100 commented on scrapper/src/main/java/edu/java/controller/ScrapperApiController.java
> +    }
Исправил в обоих случаях)

2024-03-24 11:03 UTC, merged